[package]
name = "wttg2_wiki_helper"
version = "0.1.0"
edition = "2021"

# create optimalized build
[profile.release]
lto = true
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
regex = "1.10.5"